#!/bin/bash
#
# Version = 18.0.1025.162
#

if [ ! "$1" ]; then
  echo "Provide a version pl0x.."
  svn ls https://src.chromium.org/svn/releases
  exit 1
fi

VERSION=$1

mkdir chromium
cd chromium
svn co http://src.chromium.org/svn/trunk/tools/depot_tools

PATH="$PATH":`pwd`/depot_tools

gclient config https://src.chromium.org/svn/releases/$VERSION

cat <<EOF >.gclient
solutions = [
  { "name"        : "$VERSION",
    "url"         : "https://src.chromium.org/svn/releases/$VERSION",
    "deps_file"   : "DEPS",
    "managed"     : True,
    "custom_deps" : {
    "src/third_party/WebKit/LayoutTests": None,
    "src/chrome/tools/test/reference_build/chrome": None,
    "src/chrome_frame/tools/test/reference_build/chrome": None,
    "src/chrome/tools/test/reference_build/chrome_linux": None,
    "src/chrome/tools/test/reference_build/chrome_mac": None,
    "src/third_party/hunspell_dictionaries": None,
    },
    "safesync_url": "",
  },
]
EOF

gclient sync --revision src@$VERSION

cp -rf src chromium-$VERSION
cd chromium-$VERSION
rm -rf $(find . | grep .svn\$)
cd ..
tar -cvJf chromium-$VERSION.tar.xz chromium-$VERSION

if [ -e "chromium-$VERSION.tar.xz" ]; then
  echo "chromium-$VERSION.tar.xz packaged successfully."
else
  echo "chromium-$VERSION.tar.xz packaging failed."
fi
